### ISSUE TITLE
Fix Swerve Jittering Error

### ISSUE THREAD

**Issue by Jacob1010-h** [Patribots4738/Swerve-Command-Based#10]
There is a strange issue going on with the swerve drive, where jittering keeps happening. The swerve runs smoothly when a new drive base is made and runs on new PID values.  @GalexY727, let me know if I missed anything.

Possible issues:
- The library to set the PID values is broken; maybe it is setting too high of a P value on the new Swerve?
- There could also be an issue with Command scheduling, creating timeouts between when the motor gets told to run and when it actually does run

**Comment by GalexY727** [comment]
Just gonna put this here... https://www.chiefdelphi.com/t/maxswerve-with-vortex-not-moving-properly/449976/10

**Comment by Jacob1010-h** [comment]
There might be a solution to this I would like to try out today.

**Comment by Jacob1010-h** [comment]
Sry I forgot we didn't have robotics yesterday... Lol

**Comment by Jacob1010-h** [comment]
It didn't work .... :((
