### ISSUE TITLE
Pigeon 2.0 gyro implimenation

### ISSUE THREAD

**Issue by Jacob1010-h** [Patribots4738/Swerve-Command-Based#6]
User Story:

2023 prompted us to upgrade our IMU (gyroscope) we are moving to the Pigeon 2.0 rather than the ADIS16470. I hate that imu. You can see this looking at any of Jerome’s logs because the robot tilts when it drives because the IMU thinks it is spinning. 

 

Acceptance Criteria: 

    The Pigeon needs to be implemented in place of the Yaw and complementary angles methods with the correct corresponding methods in the Pigeon class. 

    Some of the methods that will need to be used are getRotation2d() and getRotation3d(), so we don’t ever have to worry about the IMU’s “complimentary angles”.

**Comment by GalexY727** [comment]
Moving this around since it has to do with #10 ...

**Comment by RudyG252** [comment]
Soon

**Comment by Oliver-Cushman** [comment]
Soon

**Comment by Jacob1010-h** [comment]
https://www.chiefdelphi.com/t/rev-robotics-spark-flex-and-neo-vortex/442595/535?u=xander228
